--USE DB_BIBLIOTECA;

CREATE TRIGGER TRIGGER_AFTER_AUTORES
ON TB_AUTOR
AFTER INSERT, UPDATE
AS
BEGIN
	IF UPDATE(ATR_NOME)
		PRINT 'O nome do autor foi alterado'
	ELSE 
		PRINT 'O nome do autor não foi alterado'
END

--SELECT * FROM TB_AUTOR
UPDATE TB_AUTOR SET ATR_NOME = 'My name' WHERE ATR_ID = 3
UPDATE TB_AUTOR SET ATR_SOBRENOME = 'Cruz' WHERE ATR_ID = 3