USE DB_BIBLIOTECA;

ALTER TABLE TB_LIVRO 
ADD ATR_ID SMALLINT NOT NULL
CONSTRAINT FK_TB_LIVRO_TB_AUTOR_ATR_ID FOREIGN KEY(ATR_ID) REFERENCES TB_AUTOR;

ALTER TABLE TB_LIVRO 
ADD EDT_ID SMALLINT NOT NULL 
CONSTRAINT FB_TB_LIVRO_TB_EDITORA_EDT_ID FOREIGN KEY(EDT_ID) REFERENCES TB_EDITORA;