USE DB_BIBLIOTECA;

--Example 1
DECLARE @VALOR INT = 0;

WHILE @VALOR < 10
BEGIN
	PRINT 'Meu número é ' + CAST(@VALOR AS VARCHAR(5))
	SET @VALOR = @VALOR + 1
END


--Example 2 -> Show all items in TB_LIVROS where ID <= 104
DECLARE @ID_ITEM INT = 100;

WHILE @ID_ITEM <= 104
BEGIN
	SELECT LVR_NOME, LVR_PRECO
	FROM TB_LIVRO
	WHERE LVR_ID = @ID_ITEM

	SET @ID_ITEM = @ID_ITEM + 1
END


