USE DB_BIBLIOTECA;

/******* Simple *******/
SELECT * FROM TB_LIVRO

/******* Ordering the data *******/
SELECT * 
FROM TB_LIVRO
ORDER BY LVR_ID DESC 

/******* With WHERE *******/
SELECT *
FROM TB_LIVRO
WHERE LVR_NOME = 'Using Samba'

SELECT *
FROM TB_LIVRO
WHERE LVR_NOME LIKE '%Linux%'

/******* WHERE with AND or OR*******/
SELECT *
FROM TB_LIVRO
WHERE LVR_NOME LIKE '%Linux%' AND LVR_PRECO > 63

/******* TOP *******/
SELECT TOP 3 * FROM TB_LIVRO

/******* ALIAS *******/
SELECT 
	LVR_ID AS MEU_ID
	, LVR_NOME AS NOME_LIVRO
	, LVR_DATA_PUB AS 'DATA DA PUBLICAÇÃO'
FROM TB_LIVRO


/******* UNION *******/
SELECT ATR_ID FROM TB_AUTOR
UNION 
SELECT EDT_ID FROM TB_EDITORA


SELECT ATR_ID FROM TB_AUTOR
UNION ALL
SELECT EDT_ID FROM TB_EDITORA


/******* COUNT *******/
SELECT COUNT(*) AS QUANT_ITENS FROM TB_AUTOR

/******* MAX *******/
SELECT MAX(LVR_PRECO) AS PREÇO_MAXIMO FROM TB_LIVRO

/******* MIN *******/
SELECT MIN(LVR_PRECO) AS PREÇO_MINIMO FROM TB_LIVRO

/******* AVG *******/
SELECT AVG(LVR_PRECO) AS MÉDIA FROM TB_LIVRO

/******* SUM *******/
SELECT SUM(LVR_PRECO) AS SOMA_TOTAL FROM TB_LIVRO


/******* BETWEEN *******/
SELECT * FROM TB_LIVRO L WHERE L.LVR_PRECO BETWEEN 40 AND 60
SELECT * FROM TB_LIVRO L WHERE L.LVR_DATA_PUB BETWEEN '01-01-2004' AND '12-30-2009'
